### ISSUE TITLE
Option to pass raw characters to DVTM_EDITOR

### ISSUE THREAD

**Issue by mrak** [martanne/dvtm#11]
I like to use `less` as my `DVTM_EDITOR` for search and copying. I'd like to be able to use `less --RAW-CONTROL-CHARS` to maintain colorized output when entering copy/paste mode.

thanks in advance!

**Comment by martanne** [comment]
Yes I agree this would be useful. Out of interest, what other features of `less` (besides color support) do you use that are not available in `vis`?

**Comment by mrak** [comment]
I mainly use `less` because it's on all of my systems (including work) and I'm familiar with it. With `vim` or some other repurposed pager I'd want to sit down and create alternate configurations for them for `dvtm`'s purposes (and haven't gotten around to it).

I really only use `less` for the reverse search, highlight text with mouse, middle-click paste. No editing or such. My terminal let's me alt+click to select block-wise, so I don't need it supported in `less`.

I haven't found the editor-to-STDOUT workflows really ergonomic.

**Comment by mrak** [comment]
It's been a while since I coded C, but I tried to see if passing through a new `DVTM_EDITOR_ARGS` would do the trick at https://github.com/martanne/dvtm/blob/master/dvtm.c#L1057

```
env DVTM_EDITOR=less DVTM_EDITOR_ARGS="-R" dvtm
```

Followed by `ctrl-g e`.

This does indeed call `less -R` as the editor, but escape sequences seem to be stripped out prior to passing them through to the editor's STDIN.

Do you have any pointers on where to look to prevent this escape sequence stripping?

**Comment by martanne** [comment]
Avoiding the stripping won't really work, instead you have to convert the internal representation back into terminal escape sequences. Commit 5d9ab4e5 should give you an idea and a starting point. It seems to work in principle, though in my short tests I also noticed a few glitches. Would be nice if you could try it out and follow up with patches if necessary ...

**Comment by mrak** [comment]
That commit seems to work well for me. What glitches should I look out for (or steps to reproduce)?

Thanks for taking the time to spike this out

**Comment by martanne** [comment]
I was testing with a colored directory listing and when there are multiple colored items below each other only the first one was displayed in bold.

**Comment by mrak** [comment]
Thanks!
