### ISSUE TITLE
Delete key does not work in bash after using abduco to reconnect to dvtm

### ISSUE THREAD

**Issue by runrin** [martanne/dvtm#115]
I use `st`, as my terminal emulator, and the delete key works fine with `abduco` and `dvtm`.
Upon reconnecting to a detached dvtm session, the delete key no longer works in bash.

**Comment by peterjohnhartman** [comment]
I'm having a similar problem, with the HOME key (which I use for MOD).  I tested with st/xterm and abduco/dtach and I get the same results.  Curiously, however, when I use abduco + dvtm from console (outside of Xorg) it re-attaches just fine.

**Comment by runrin** [comment]
actually it works fine in konsole, and xterm, as well as i the system console for me. what terminal emulator do yoyu use @peterjohnhartman ?

**Comment by runrin** [comment]
@peterjohnhartman the issue goes away if i hit enter after reconnecting. give that a try and see if it fixes your issue as well. it happens with just abduco though, so it's definitely not a dvtm issue.
