### ISSUE TITLE
Can't change escape key with abduco

### ISSUE THREAD

**Issue by tapir** [martanne/dvtm#15]
```abduco -c session_name``` will automatically start dvtm. How can I set a non default escape key to dvtm? 
I've put an alias to basrch as ```alias dvtm=dvtm -e ^Oo``` but that only works if I run dvtm on its own.

**Comment by martanne** [comment]
With the latest [abduco commits](https://github.com/martanne/abduco/commit/fdd0c4163ffc8e30f0643af8f76457b89428bfd3) the following should work:

    $ export ABDUCO_CMD="dvtm -m ^o"
    $ abduco -c session_name

also you seem to specify a key sequence (made up by multiple letters). abduco and dvtm will both only look at most one character. That is `-m ^oignored` will have the same effect as `-m ^o`.
