### ISSUE TITLE
sourced files on dvtm start

### ISSUE THREAD

**Issue by agreif** [martanne/dvtm#16]
Hi,
I am using dvtm 0.14 on current OpenBSD with korn shell.
my .profile sources the .kshrc with all aliases like ll="ls -la"

after starting dvtm, I dont see any of my aliases.
It seems that dvtm does not read neither .profile, nor .kshrc
So wehn using dvtm, after I create a new shell, I always have to manually source my .kshrc.

questions:
1) are any dot-files sourced by dvtm on its statup? If yes what are they called and where are they expected?
2) how can I tweak dvtm to source my ~/.kshrc

thanks,
Alex.

**Comment by martanne** [comment]
dvtm does not source any shell startup scripts, it simply creates a *non* login / interactive shells. This is different from e.g. tmux which creates login shells.

I think conceptually the dvtm behaviour is the right thing to do.

Many shells use different startup files depending on whether they are executed as a login shell or not. For example bash uses (among other things) `~/.profile` for login shells and `~/.bashrc` for interactive shells. I'm not familiar with the korn shell, but according to the [manual page](http://www.openssh.com/cgi-bin/man.cgi/OpenBSD-current/man1/ksh.1?query=ksh&sec=1) the `$ENV` variable is sourced for interactive shells. You could try to add:

    export ENV=$HOME/.kshrc

to your `.profile`. Maybe @Pyrohh yould chime in, as he is familiar with OpenBSD?

Another, although a bit ugly, solution would be to create a `/bin/dvtm-shell` wrapper script:

```
#!/bin/sh
export SHELL=/bin/sh
exec /bin/sh -l
```

and then start dvtm as follows:

    SHELL=/bin/dvtm-shell dvtm

**Comment by Pyrohh** [comment]
> to your .profile. Maybe @Pyrohh yould chime in, as he is familiar with OpenBSD?

The use of `ENV` is exactly what I would recommend, assuming @agreif isn't already doing that. I have all environment variables set in `~/.profile`, and everything else set in `~/.kshrc, including aliases, some functions, `stty -ixon`, `set -o emacs`, etc.

Judging from my own experience non of the wrappers proposed above should be needed, just define `ENV` at the bottom of your `~/.profile`. This segment from `man ksh` should be read if you're still confused:

```
     If the ENV parameter is set when an interactive shell starts (or, in the
     case of login shells, after any profiles are processed), its value is
     subjected to parameter, command, arithmetic, and tilde (‘~’) substitution
     and the resulting file (if any) is read and executed.  In order to have
     an interactive (as opposed to login) shell process a startup file, ENV
     may be set and exported (see below) in $HOME/.profile - future
     interactive shell invocations will process any file pointed to by $ENV:

           export ENV=$HOME/.kshrc

     $HOME/.kshrc is then free to specify instructions for interactive shells.
     For example, the global configuration file may be sourced:

           . /etc/ksh.kshrc

     The above strategy may be employed to keep setup procedures for login
     shells in $HOME/.profile and setup procedures for interactive shells in
     $HOME/.kshrc.  Of course, since login shells are also interactive, any
     commands placed in $HOME/.kshrc will be executed by login shells too.

     The exit status of the shell is 127 if the command file specified on the
     command line could not be opened, or non-zero if a fatal syntax error
     occurred during the execution of a script.  In the absence of fatal
     errors, the exit status is that of the last command executed, or zero, if
     no command is executed.
```

**Comment by agreif** [comment]
Hi,
thanks a lot for the quick answer, as suggested in .profile

    export ENV=$HOME/.kshrc

solved my problem.

Keep up the good work,
thanks,
Alex.
