### ISSUE TITLE
Trouble compiling 0.14 on FreeBSD

### ISSUE THREAD

**Issue by adriangrigore** [martanne/dvtm#2]
My `config.mk`:
   
    # dvtm version
    VERSION = 0.14

    # Customize below to fit your system

    PREFIX ?= /usr/local
    MANPREFIX = ${PREFIX}/man
    # specify your systems terminfo directory
    # leave empty to install into your home folder
    TERMINFO := ${DESTDIR}${PREFIX}/share/terminfo

    INCS = -I.
    LIBS = -lc -lutil -lncurses
    CPPFLAGS = -D_POSIX_C_SOURCE=200809L -D_XOPEN_SOURCE=700 -D_XOPEN_SOURCE_EXTENDED -D__BSD_VISIBLE
    CFLAGS += -std=c99 ${INCS} -DVERSION=\"${VERSION}\" -DNDEBUG ${CPPFLAGS}
    LDFLAGS += ${LIBS}

    DEBUG_CFLAGS = ${CFLAGS} -UNDEBUG -O0 -g -ggdb -Wall -Wextra -Wno-unused-parameter

    CC ?= cc
    STRIP ?= strip

The error i'm getting when running `make`:

    cleaning
    dvtm build options:
    CFLAGS   = -O2 -pipe   -std=c99 -I. -DVERSION="0.14" -DNDEBUG -D_POSIX_C_SOURCE=200809L -D_XOPEN_SOURCE=700 -D_XOPEN_SOURCE_EXTENDED -D__BSD_VISIBLE
    LDFLAGS  =  -lc -lutil -lncurses
    CC       = cc
    CC dvtm.c
    CC vt.c
    CC -o dvtm
    dvtm.o: In function `drawbar':
    dvtm.c:(.text+0x272b): undefined reference to `waddnwstr'
    cc: error: linker command failed with exit code 1 (use -v to see invocation)
    *** Error code 1

    Stop.

**Comment by martanne** [comment]
Try linking against `libncursesw` i.e. set `LIBS = -lc -lutil -lncursesw`

**Comment by adriangrigore** [comment]
Worked, thanks!
