### ISSUE TITLE
dvtm unsets LS_COLORS

### ISSUE THREAD

**Issue by pvater** [martanne/dvtm#21]
is that on purpose (why)?

it doesn't do that when i set DVTM_TERM to "screen" or "xterm" before launching dvtm, or if i set TERM to either of those from within dvtm.

but with that there's at least one (new) issue: the cursor isn't properly reset, or something - let's say my cursor is somewhere in the middle of the screen (for example, after i do "echo -e 'foo\nfoo\nfoo\nfoo\nfoo'). then, when i open and close some fullscreen program (e.g. "man man"), the cursor is suddenly on the 1st line of the screen, not where it was before, and the output from before (the 5 "foo"s) is still there.

is that expected behavior?

thanks!

(btw this happens with dvtm-0.15 on linux)

**Comment by martanne** [comment]
dvtm should not unset the `LS_COLORS` environmental variable. More likely your shell startup scripts do not set it (or only if `$TERM` is a "known" value such as `xterm` or `screen`.

Also keep in mind that dvtm creates *non*-login shells (as apposed to for example tmux which AFAIK creates login shells), make sure you are modifying the correct shell startup script.

**Comment by pvater** [comment]
yes, you're right. it was because i aliased "ls" to "ls --color=auto". it works fine with "--color=always" instead. thanks!

**Comment by pvater** [comment]
actually what i said is wrong. i just didn't set LS_COLORS correctly - i used to reset it for every non-login shell (with the dircolors command, and within dvtm it just gets set to an empty string), it works fine when i only set it for login-shells. so as you said.
