### ISSUE TITLE
Setting MOD to Ctrl + Space

### ISSUE THREAD

**Issue by sshbio** [martanne/dvtm#24]
I tried setting the modifier to Ctrl + Space, but I could not get any result, the mapping simply being ignored.

I tested the following in my config.h:

```C
#define MOD  CTRL(' ')
```

```C
#define MOD  CTRL('@')
```

```C
#define MOD  CTRL('<control-space-character>')
```

The control space character have been inserted with vim, with `<c-v>` `<c-space>` which inserted something represented as `^@`.

You may know better than me how terminal keyboard input is complex, and this is not really a priority for me.

Thank you for having a look at this, and for starting up this great project.

**Comment by sshbio** [comment]
For reference, I've seen the issue being discussed on the mailing list archive:

http://lists.suckless.org/dev/1401/19560.html

**Comment by martanne** [comment]
This should now work by setting:
```C
#define MOD  CTRL(' ')
```
or running
```
$ dvtm -m '^ '
```

**Comment by sshbio** [comment]
This works in both tty and X11, with or without abduco.  Even more impressive to me: you fixed the issue by removing lines.

Thank you very much!
