### ISSUE TITLE
[suggestion/patch] Show tag name in title bar.

### ISSUE THREAD

**Issue by sshbio** [martanne/dvtm#25]
I often have multiple tags displayed at once, and it gets a bit hard to know which window has which tag: I need to switch to each individual tag and check if my window is there.

What I propose is having the name of the tags displayed in the window bar, next to the title.

I made [this patch](https://github.com/martanne/dvtm/files/231094/dvtm-tag-in-title.txt):

```diff
diff --git a/Makefile b/Makefile
index 09d1080..baba2f6 100644
--- a/Makefile
+++ b/Makefile
@@ -16,13 +16,13 @@ config.h:
 
 .c.o:
 	@echo CC $<
-	@${CC} -c ${CFLAGS} $<
+	@${CC} -c -lm ${CFLAGS} $<
 
 ${OBJ}: config.h config.mk
 
 dvtm: ${OBJ}
 	@echo CC -o $@
-	@${CC} -o $@ ${OBJ} ${LDFLAGS}
+	@${CC} -o $@ ${OBJ} -lm ${LDFLAGS}
 
 debug: clean
 	@make CFLAGS='${DEBUG_CFLAGS}'
diff --git a/dvtm.c b/dvtm.c
index c6440ab..ddf2f39 100644
--- a/dvtm.c
+++ b/dvtm.c
@@ -13,6 +13,7 @@
 #include <stdlib.h>
 #include <unistd.h>
 #include <stdint.h>
+#include <math.h>
 #include <wchar.h>
 #include <sys/select.h>
 #include <sys/stat.h>
@@ -405,9 +406,20 @@ draw_border(Client *c) {
 		c->title[maxlen] = '\0';
 	}
 
-	mvwprintw(c->window, 0, 2, "[%s%s#%d]",
+	char tagnames[12 * LENGTH(tags)] = "";
+
+	for (int j = c->tags, i = LENGTH(tags) - 1; i >= 0; --i) {
+		if (j >= pow(2, i)) {
+			j = j - pow(2, i);
+			strcat(tagnames, tags[i]);
+			strcat(tagnames, " | ");
+		}
+	}
+
+	mvwprintw(c->window, 0, 2, "[%s%s%s#%d]",
 	          *c->title ? c->title : "",
 	          *c->title ? " | " : "",
+	          tagnames,
 	          c->order);
 	if (t)
 		c->title[maxlen] = t;
```

I am a beginner with C, so it may not be written in a very good C: I used the `pow()` function and then had to use one more library just for this.

**Comment by sshbio** [comment]
Maybe it is possible to display the tag numbers rather than the tag names, to save space in the title bar.  The implementation would be rather the same.

**Comment by martanne** [comment]
I will have to try it, but my initial reaction is that it probably uses too much screen space?

Maybe we could use different colors per tag or something like that. However we would still need to display a symbol (the number?) per tag. Although displaying such a rainbow might also be a distraction. 

I generally use topical tags for things like "irc", "mail", "devel" and it is implicitly clear which window belongs to which tag. Also if multiple tags are selected, the tagbar at the top indicates which ones are currently active.

As for the code, in C it is quite common to do low level bit shifting, `1 << i` as done in the `drawbar` function should be sufficient, no need for `math.h`. If you still need the math library for something it should be added to the [`$LIBS` variable in `config.mk`](https://github.com/martanne/dvtm/blob/master/config.mk#L13) instead of directly to the `Makefile`.

**Comment by sshbio** [comment]
After using it a few, *feels* like too much screen space is used.  Maybe the tag numbers, but I think dwm approach was still the best: a mark on the tags that the window have, on the tagbar.

I will try something and hopefully I will get it to work.  If I do I will come back with a screencast.

I'm still learning C, trying to stick to suckless way, and you are really helping with these tips.  Thank you for taking the time to explain.

**Comment by sshbio** [comment]
Here is a new proposition: Rather than displaying each of the tag names in borders, the format string used to display a tag in the bar, `TAG_SYMBOL` can be different for when the tag owns a focused.

As an example, with:

```
#define TAG_SYMBOL "[%s]"
#define TAG_SYMBOL_FOCUSED "(%s)"
```
- Window 1: tag `1`, `3`
- Window 2: tag `2`, `3`

Selecting the tag `3`

```
(1)[2](3)[4][5][]=[                   ]
──[#1]─────────────┬──[#2]─────────────
> Selected         │> 
```

```
[1](2)(3)[4][5][]=[                   ]
──[#1]─────────────┬──[#2]─────────────
>                  │> Selected
```

So adding the option to config.def.h (this will break compatibilities of older config.h, unfortunately).

```diff
diff --git a/config.def.h b/config.def.h
index 643a281..8e6a77a 100644
--- a/config.def.h
+++ b/config.def.h
@@ -45,6 +45,8 @@ static Color colors[] = {
 #define SCROLL_HISTORY 500
 /* printf format string for the tag in the status bar */
 #define TAG_SYMBOL   "[%s]"
+/* printf format string for the tags that current focused window */
+#define TAG_SYMBOL_FOCUSED   "[%s]"
 /* curses attributes for the currently selected tags */
 #define TAG_SEL      (COLOR(BLUE) | A_BOLD)
 /* curses attributes for not selected tags which contain no windows */
```

Adding a condition, to choose the format string (much simpler with bitwise operators, thank you for the tip).

```
diff --git a/dvtm.c b/dvtm.c
index c6440ab..000300d 100644
--- a/dvtm.c
+++ b/dvtm.c
@@ -317,6 +317,7 @@ static void
 drawbar(void) {
 |      int sx, sy, x, y, width;
 |      unsigned int occupied = 0, urgent = 0;
+|      Client *c = sel;
 |      if (bar.pos == BAR_OFF)
 |      |       return;
_
@@ -339,7 +340,12 @@ drawbar(void) {
 |      |       |       attrset(TAG_OCCUPIED);
 |      |       else
 |      |       |       attrset(TAG_NORMAL);
-|      |       printw(TAG_SYMBOL, tags[i]);
+|      |       if (c) {
+|      |       |       if (c->tags & (1 << i))
+|      |       |       |       printw(TAG_SYMBOL_FOCUSED , tags[i]);
+|      |       |       else
+|      |       |       |       printw(TAG_SYMBOL , tags[i]);
+|      |       }
 |      }
```

And now, while we switch client, we also need to redraw the status bar, and not only the border.

```
_
 |      attrset(TAG_NORMAL);
@@ -585,6 +591,7 @@ focus(Client *c) {
 |      |       |       draw_border(c);
 |      |       |       wnoutrefresh(c->window);
 |      |       }
+|      |       drawbar();
 |      }
 |      curs_set(c && !c->minimized && vt_cursor_visible(c->term));
 }
```

**Comment by sshbio** [comment]
```
⡏⣭⡍⡇⡪⠡⠴⠰⠳⠗⠻⠬⠘⠡⠆⠈⠅⡏⣭⡍⡇
⠧⠭⠥⠇⠆⠄⢄⣄⣔⣖⣖⣖⣄⡄⠄⠄⠄⠧⠭⠥⠇
⠫⡭⠗⠍⠁⣴⠋⠉⠁⠀⠀⠀⠀⠉⢯⡒⡞⢪⣚⢸⡆
⣐⡅⡨⠅⣸⡇⠃⠀⠀⠀⠐⠀⠀⠈⠘⢻⢀⡄⣋⢃⠃
⠤⢥⠟⠅⢿⡇⠀⣠⣤⠀⠀⣠⣄⠰⢽⣜⡐⢺⡊⢀⠀
⡼⠁⣠⠅⠘⡇⠈⠙⠋⠁⠈⠙⠛⠋⠈⡏⢠⡀⠏⣉⠃
⠁⢚⡨⠅⠇⡇⠀⠀⠀⣠⢠⠀⠀⠠⣼⠓⠆⢺⡊⠮⠅
⡎⡫⡞⠅⠀⢰⣄⢠⡄⣛⣸⣤⣄⣸⡽⡊⢠⡀⠤⢗⡂
⡥⠤⠭⡅⠇⣩⣿⡮⣂⢲⢂⣂⢻⡯⢺⣦⡏⠍⡿⠟⠁
⡇⠿⠇⡇⡇⣾⡏⠛⠿⢿⡟⣷⢟⣻⡿⢑⠩⢽⠅⣯⠁
⠉⠉⠉⠁⠁⠉⠁⠀⠈⠁⠀⠀⠈⠉⠉⠈⠁⠈⠈⠁⠀
```

This is just because I like your avatar, and wanted to try this.  Render may vary according to your font.

**Comment by sshbio** [comment]
[Here is the patch](https://raw.githubusercontent.com/sshbio/dot/80f93aeeca614ec977f24b6bc2b53bb4c9fd59dd/src/dvtm/dvtm-focused-tags.diff), if you want, I can make a pull request with it listed in the patch list.
