### ISSUE TITLE
[enh] launch command in active dvtm

### ISSUE THREAD

**Issue by lanodan** [martanne/dvtm#3]
I’d like to launch command in dvtm (equivalent of screen: ``^a:screen <command>``). Maybe something vim/screen-like to configure dvtm while running.

**Comment by martanne** [comment]
Why? What kind of commands would you like to enter? There is a named pipe based mechansim for this sort of thing. Specify the `-c` command line argument when starting dvtm as in:

    dvtm -c /tmp/command-fifo

Then within dvtm an environment variable `$DVTM_CMD_FIFO` is set, pointing to the named pipe. Thus you can execute commands via `echo create > $DVTM_CMD_FIFO`. Notice that by default `create` is the only [recognized command](https://github.com/martanne/dvtm/blob/master/config.def.h#L197).

In the future the named pipe will probably be replaced by an unix domain socket, thus allowing bidirectional communication.
