### ISSUE TITLE
compilation error fix for osx 10.11

### ISSUE THREAD

**Issue by pvtmert** [martanne/dvtm#30]
there was an error in v0.15 where sigwinch seems to be 'undefined' within default includes in osx

actually seems available on sys/signal.h but doesn't compile.

added definition if not defined already.

homebrew patchfile: https://github.com/Homebrew/formula-patches/blob/master/dvtm/patch-vt.h-compat.patch

**Comment by martanne** [comment]
Thanks for the report, however hard coding this is not a good solution. I don't have access to a Mac OS X system, but according to Google `SIGWINCH` is available if `_DARWIN_C_SOURCE` is defined. This seems to be the case in the [homebrew formula](https://github.com/pvtmert/homebrew-core/blob/d3c8b070e1cd1ae90eef418d0cdb6d89fd13a9dd/Formula/dvtm.rb#L22). Hence, I'm a bit puzzled as to why this would fail?

The following should work:
```
CFLAGS=-D_DARWIN_C_SOURCE make
```

**Comment by pvtmert** [comment]
yep, looks like that fixes it. going to update formula then...
