### ISSUE TITLE
Glitchy rendering when using kakoune

### ISSUE THREAD

**Issue by lenormf** [martanne/dvtm#33]
Hi,

My main editor is [Kakoune](https://github.com/mawww/kakoune), and I can't seem to get it to render properly in a `dvtm` session. The first "frames" are rendered just fine, but a couple seconds after I've started typing things in, the status bar starts being rendered over the buffer, text randomly disappears, whitespace get inserted into the buffer etc. Using `MOD+r` always resets the terminal back to what it should be though (everything is displayed properly).

I've tried changing the `DVTM_TERM` variable to `screen`/`xterm`, using `ncurses5` over `ncurses6`, and I've read issues seemingly relevant that have already been created, but nothing I've tried has had any effect on the glitch.

What can I do to pinpoint precisely the cause of this faulty rendering, and how can I work around/fix it ?

Thanks.

**Comment by martanne** [comment]
Thanks for the report. Did you install the dvtm terminfo description (`tic -s dvtm.info`, or `make install`)?

Also what version of the relevant tools (dvtm & kak) did you use? Latest git?

If I find the time, I will try to reproduce the problem.

**Comment by lenormf** [comment]
Hi,

I'm using `dvtm-0.15` on archlinux, the package has been installed with `make install` and I have the following files in my system:
```
/usr/bin/dvtm
/usr/bin/dvtm-status
/usr/share/man/man1/dvtm.1.gz
/usr/share/terminfo/d/dvtm
/usr/share/terminfo/d/dvtm-256color
```

I'm also using `ncurses-6.0` (which `kakoune` uses to do the rendering).

Thanks.

**Comment by greduan** [comment]
I can reproduce this, I am using the `dvtm` package provided by the [official Arch Linux packages](https://www.archlinux.org/packages/community/x86_64/dvtm/), not inside `abduco`.

I just had to open a file and move my cursor down continually and this is the result:

![2016-09-28-205530_1366x768_scrot](https://cloud.githubusercontent.com/assets/2314074/18927894/119379c4-85be-11e6-84b8-9a8dbe8be2eb.png)

**Comment by greduan** [comment]
Setting inside `kak` `:set global ui_options ncurses_set_title=false` fixes the issue.

Is this something dvtm needs to fix because it's ncurses setting the title or is it because of how kakoune is setting the title? I think it's the former but I dunno.

**Comment by mawww** [comment]
I think this is more of a Kakoune bug, it sets the title using an escape sequence without making sure the terminal supports it. Not sure how to know if OSC 2 is handled though.

That said, should not dvtm gracefully ignore OSC commands it does not support ?

**Comment by martanne** [comment]
> I think this is more of a Kakoune bug, it sets the title using an escape sequence without making sure the terminal supports it.

dvtm actually does the same, except when running in the linux console which doesn't (or didn't?) support it.

> Not sure how to know if OSC 2 is handled though

I too would be interested to know whether there is a simple way to check that.

Back to the issue, dvtm [supports the relevant xterm extension to set the window title](https://github.com/martanne/dvtm/blob/c38c27b0b738f5012baf6bd9599ff4d8b9779e7e/vt.c#L1148). I don't have Kakoune at hand, but something like
```
printf '\033]2;Test - Kakoune\007'
```
works as expected.

There was a problem that dvtm itself did not properly pass on the given window title (see #32) but this shouldn't matter here?

**Comment by mawww** [comment]
I think the root of the problem is the use of printf for title handling, mixing buffered and unbufferred output (vt_write uses directly write). The fflush that was added will probably make the problem go away, but why use bufferred output if you dont actually buffer.

**Comment by lenormf** [comment]
I noticed that rendering corruption didn't happen in kakoune until a certain amount of characters were displayed (usually) around ten. So I went and opened a shell in `dvtm` (without kakoune), set the title a around twenty times in a row using the last status that was displayed before the artifact appeared in kakoune (`printf '\033]2;*scratch* 16:1 [+] insert 1 sel - unnamed0@[29066] - Kakoune\007'`, executed ~20 times), and surely enough rendering was corrupted (even more badly than when experienced within kakoune if I may say so).

**Comment by martanne** [comment]
@mawww I don't think that is the case, `vt_write` is only used for the pseudo tty. However the output stream is shared with curses which depending on the version might do its own buffering or use stdio (see also the `NCURSES_NO_SETBUF` environment variable). By the way Kakoune seem to do [basically the same thing](https://github.com/mawww/kakoune/blob/master/src/ncurses_ui.cc#L410-L418) as dvtm.

@lenormf do you still get corruptions with the [added flush](https://github.com/martanne/dvtm/commit/2673e9d08aba1dfbd405fb6fa13169fed7ce5c34)? This issue might actually be the same as reported in #14 which according to @Link-Satonaka now works.

**Comment by lenormf** [comment]
Sorry @martanne I hadn't seen your last commit. It seems to have fixed the issue.

**Comment by mawww** [comment]
@martanne yeah, I did not realize it was ncurses under the hood.

**Comment by lenormf** [comment]
Since no question was left unanswered, closing this for now.
