### ISSUE TITLE
Alt backspace doesn't work with `zsh`

### ISSUE THREAD

**Issue by lenormf** [martanne/dvtm#36]
Hi,

I haven't investigated this issue, all I can say is that I'm using `zsh` with `dvtm` 0.15 and `alt-backspace` inserts a newline instead of doing a `^W`.

Thanks.

**Comment by moosotc** [comment]
Not only that, also when dvtm if first started in st the title reads dvtm and even though following is present in .zshrc title is never updated on command execution, after pressing alt-backspace though title is updated properly and continues to function as intended

.zshrc portion
xtitle ()
{
    printf "\033]0;$1\007"
}
precmd ()
{
    xtitle "${PWD}"
}

**Comment by moosotc** [comment]
The issue is not limited to zsh/st. As alt-backspace doesn't work in linux console too, following crude hack does "fix" things for me:

diff --git a/dvtm.c b/dvtm.c
index 434c0af..e8c1e65 100644
--- a/dvtm.c
+++ b/dvtm.c
@@ -881,7 +881,10 @@ keypress(int code) {
 		if (is_content_visible(c)) {
 			c->urgent = false;
 			if (code == '\e')
-				vt_write(c->term, buf, len);
+				if (len == 2 && buf[1] == 7)
+					vt_keypress(c->term, 037 & 'w');
+				else
+					vt_write(c->term, buf, len);
 			else
 				vt_keypress(c->term, code);
 		}

**Comment by josuah** [comment]
Here: https://github.com/martanne/dvtm/blob/master/dvtm.c#L883

You may need to edit the comment and add `\`\`\`` before and after the diff to prevent github to mess it up.

**Comment by moosotc** [comment]
Josuah Demangeon⠠⠵ <notifications@github.com> writes:

> Here: https://github.com/martanne/dvtm/blob/master/dvtm.c#L883
>
> You may need to edit the comment and add `\`\`\`` before and after the
> diff to prevent github to mess it up.

Thanks. I already created local dvtm mirror earlier:

https://github.com/moosotc/dvtm/commit/9edb011113e08707137b0dbd3f5eac2b3859cb75

-- 
mailto:moosotc@gmail.com

**Comment by josuah** [comment]
Nice.  This patch makes sense to me: it could be a feature of dwm: converting alt-backspace to ctrl + w.

Thes `st` term converts `Scroll up` and `Scroll down` mouse events to `Ctrl e` and `Ctrl y` to scroll in `vim` and `less`.

**Comment by moosotc** [comment]
Josuah Demangeon⠠⠵ <notifications@github.com> writes:

> Nice.  This patch makes sense to me: it could be a feature of dwm:
> converting alt-backspace to ctrl + w.

Glad you liked it.

>
> Thes `st` term converts `Scroll up` and `Scroll down` mouse events to
> `Ctrl e` and `Ctrl y` to scroll in `vim` and `less`.

Hm... It probably needs some configuration (i.e. doesn't work out of the
box for me here)

-- 
mailto:moosotc@gmail.com

**Comment by josuah** [comment]
@moosotc

```
$ which st
/usr/bin/st
```

You are right, it was the system one, probably with [this config file](https://git.archlinux.org/svntogit/community.git/tree/trunk/config.h?h=packages/st).
