### ISSUE TITLE
No color when using "ls" command

### ISSUE THREAD

**Issue by Fougasse** [martanne/dvtm#37]
Hi,

when I use the _ls_ command on my terminal while using _dvtm_, colors doesn't appear. However, everything else - like _Vim_ for example - works fine. Is there a way to correct it ?

My configuration:
- OS: Parabola GNU/Linux-libre ;
- WM: dwm ;
- Terminal: st ;
- dvtm compiled from sources.

Thanks.

**Comment by josuah** [comment]
I propose to make sure you installed terminfo with the `tic` command.  Usually it is done automatically...

```sh
tic -s dvtm.info
```

It may also be due to ls not recognizing dvtm as a valid terminal type.

Can you try to set the `TERM=xterm-260color` variable to something very common, like:

```
$ dvtm
$ export TERM=xterm-256color
$ ls
```

**Comment by Fougasse** [comment]
Thank you for the answer.

I have done this command before:

        tic -s dvtm.info

because the *README.md* file advices to do it but it still does not work.

For the other solution I tried this `TERM=xterm-256color`, I have also installed *xterm* because I did not installed it on computer before. Colors appear with *ls* but nothing works in Vim. However, if I try 
this:

        $ dvtm
        $ export TERM=st-256color
        $ ls

it works fine and Vim works too but when I quit Vim, the prompt appears above the first line of the terminal, not after the `vim` command as it should be. Do you have another solution?

Thanks again!

**Comment by rpmohn** [comment]
Have you tried TERM=dvtm-256color?

**Comment by Fougasse** [comment]
Yes, I did. But it's the same problem: colors doesn't appear with `ls --color`.

**Comment by Fougasse** [comment]
I've found a possible solution. I added this:

        LS_COLORS='rs=0:di=01;34:ln=01;36:mh=00:pi=40;33:so=01;35:do=01;35:bd=40;33;01:cd=40;33;01:or=40;31;01:mi=00:su=37;41:sg=30;43:ca=30;41:tw=30;42:ow=34;42:st=37;44:ex=01;32:*.tar=01;31:*.tgz=01;31:*.arc=01;31:*.arj=01;31:*.taz=01;31:*.lha=01;31:*.lz4=01;31:*.lzh=01;31:*.lzma=01;31:*.tlz=01;31:*.txz=01;31:*.tzo=01;31:*.t7z=01;31:*.zip=01;31:*.z=01;31:*.Z=01;31:*.dz=01;31:*.gz=01;31:*.lrz=01;31:*.lz=01;31:*.lzo=01;31:*.xz=01;31:*.bz2=01;31:*.bz=01;31:*.tbz=01;31:*.tbz2=01;31:*.tz=01;31:*.deb=01;31:*.rpm=01;31:*.jar=01;31:*.war=01;31:*.ear=01;31:*.sar=01;31:*.rar=01;31:*.alz=01;31:*.ace=01;31:*.zoo=01;31:*.cpio=01;31:*.7z=01;31:*.rz=01;31:*.cab=01;31:*.jpg=01;35:*.jpeg=01;35:*.gif=01;35:*.bmp=01;35:*.pbm=01;35:*.pgm=01;35:*.ppm=01;35:*.tga=01;35:*.xbm=01;35:*.xpm=01;35:*.tif=01;35:*.tiff=01;35:*.png=01;35:*.svg=01;35:*.svgz=01;35:*.mng=01;35:*.pcx=01;35:*.mov=01;35:*.mpg=01;35:*.mpeg=01;35:*.m2v=01;35:*.mkv=01;35:*.webm=01;35:*.ogm=01;35:*.mp4=01;35:*.m4v=01;35:*.mp4v=01;35:*.vob=01;35:*.qt=01;35:*.nuv=01;35:*.wmv=01;35:*.asf=01;35:*.rm=01;35:*.rmvb=01;35:*.flc=01;35:*.avi=01;35:*.fli=01;35:*.flv=01;35:*.gl=01;35:*.dl=01;35:*.xcf=01;35:*.xwd=01;35:*.yuv=01;35:*.cgm=01;35:*.emf=01;35:*.ogv=01;35:*.ogx=01;35:*.aac=00;36:*.au=00;36:*.flac=00;36:*.m4a=00;36:*.mid=00;36:*.midi=00;36:*.mka=00;36:*.mp3=00;36:*.mpc=00;36:*.ogg=00;36:*.ra=00;36:*.wav=00;36:*.oga=00;36:*.opus=00;36:*.spx=00;36:*.xspf=00;36:';
        export LS_COLORS`

to my `/etc/profile` file.

**Comment by martanne** [comment]
On some systems `dircolors(1)` seems to be used to set the `LS_COLORS` environment variable.
Also at least with GNU ls, which you seem to be using, you can force colors with `ls --color=always`.

As you noticed this seems to be an issue with your shell startup scripts.

**Comment by pepa65** [comment]
I had a similar problem. `ls --color=always` didn't work when I had `TERM=dvtm-256color` but ls worked normally when `TERM=xterm-256color`. (`tic -s dvtm.info` also didn't help.)
