### ISSUE TITLE
really dwm behaviour?

### ISSUE THREAD

**Issue by shibumi** [martanne/dvtm#4]
Hello I am thinking about forking dvtm because I want some really dwm behaviour. I don't want to press the modkeys CTRL+g first.. I just want to press Mod4+Enter for spawning another window. What do you mean is this possible or not?

best regards

Chris

**Comment by martanne** [comment]
What is your `Mod4` mapped to? The problem is curses doesn't provide access to these modifier keys, it would probably require [libtermkey](http://www.leonerd.org.uk/code/libtermkey/) or similar to handle these special keys.

**Comment by shibumi** [comment]
super-key/windows-key.. I want really dwm behaviour.. so I just want to hold down windows-key and press the option not: CTRL+g and after this option

**Comment by martanne** [comment]
Terminal input in general is a mess. You can try whether the [libtermkey demo application](http://www.leonerd.org.uk/code/libtermkey/overview.html) recognizes your favorite key bindings. If it does then they could probably be used in dvtm.

**Comment by shibumi** [comment]
mhh thx I will think about it ..
