### ISSUE TITLE
super key as MOD

### ISSUE THREAD

**Issue by rotsix** [martanne/dvtm#48]
Hi,

I just discovered dvtm and started loving it for my Pi, but I have a question.

Is it possible to bind the super key (windows key) as MOD? I tried Mod4Mask but that's for X11 if i remember well.

Thanks, and thanks for dvtm!

**Comment by josuah** [comment]
I do not think this is possible to transmit the Mod4Mask to the terminal.  You can try in the TTY:

```
read
```

then press `Ctrl` + `v`, then `Super` + `any key`.  The key you pressed will be displayed directly, without any difference with the key pressed directly.

I also asked if it would be easy to use `Alt` as a modifier (#39), but it was not easy.

What I do instead is `Ctrl` + `Space`, which is `CTRL('@')` in config.h.

**Comment by Piczel** [comment]
you're right, that's not possible.
But don't you think that it would be possible to use the w$ key as mod ?

It not, `ctrl + space` is good, but as a lazy boy, 2 keys are always harder than 1 !

**Comment by Piczel** [comment]
Mh, weird issue,

neither `CTRL('@')` nor `dvtm -m '^@'` are working.

arch 4.8.13
dvtm-0.15

**Comment by josuah** [comment]
Make suce to have the latest version.  This was no lt passixle bofore [this change](https://github.com/martanne/dvtm/commit/c38c27b0b738f5012baf6bd9599ff4d8b9779e7e).

**Comment by martanne** [comment]
As @josuah correctly pointed out super can't really be detected. You could probably use `loadkeys(1)` to change the console key mappings. Personally I would recommend against that because I want consistent key bindings independent of the environment (TTY, X11, ...)
