### ISSUE TITLE
"qqqqqqqq" instead of lines on OpenBSD 5.6

### ISSUE THREAD

**Issue by adriangrigore** [martanne/dvtm#5]
dvtm doesn't draw lines on Open BSD, instead it shows weird characters (compiled with -lncursesw).

**Comment by adriangrigore** [comment]
Setting NCURSES_NO_UTF8_ACS=1 doesn't work.

**Comment by adriangrigore** [comment]
Ok, I was running inside putty, this fixed it for me: http://stackoverflow.com/a/26426723.

**Comment by sshbio** [comment]
I get this issue while starting dvtm in abduco, in X11 terminal st, and then attaching the abduco session is TTY framebuffer.

Starting dvtm in TTY and then attaching it to st in X11 does not provoke the issue.
