### ISSUE TITLE
REQ: Hide empty tag bar

### ISSUE THREAD

**Issue by pepa65** [martanne/dvtm#58]
As of now, I'm not using tags, so I would like to hide the tag bar.
This is probably already possible, because the dvtm in the Ubuntu repos is like that. But I can't get it to work editing `config.h`. I tried `const char tags[][8] = {};` but that didn't get rid of the whole line.

**Comment by pepa65** [comment]
Hmm, it seems the older version (0.12) just didn't have a tag bar... So it would be a real feature to have it hidden as an option.

**Comment by josuah** [comment]
DVTM's manpage has the info you want.  Man pages always have the info we want ;)

`man dvtm` in a terminal:

---

...
<dt class="list-tag" style="margin-top: 1.00em;">
<b class="cmd">Mod-b</b></dt>
<dd class="list-tag" style="margin-left: 1.00ex;">
Change to bottom stack tiling layout.</dd>
<dt class="list-tag" style="margin-top: 1.00em;">
<b class="cmd">Mod-g</b></dt>
<dd class="list-tag" style="margin-left: 1.00ex;">
Change to grid layout.</dd>
<dt class="list-tag" style="margin-top: 1.00em;">
<b class="cmd">Mod-s</b></dt>
<dd class="list-tag" style="margin-left: 1.00ex;">
Show/hide the status bar.</dd>
<dt class="list-tag" style="margin-top: 1.00em;">
<b class="cmd">Mod-S</b></dt>
<dd class="list-tag" style="margin-left: 1.00ex;">
Toggle position of the status bar between top and bottom.</dd>
<dt class="list-tag" style="margin-top: 1.00em;">
<b class="cmd">Mod-r</b></dt>
<dd class="list-tag" style="margin-left: 1.00ex;">
</dd>
...

---

There is also an option in `config.h` to choose whether the tag bar (status line) is shown at startup or whether you have to toggle it with the keybinding:

https://github.com/martanne/dvtm/blob/master/config.def.h#L39

**Comment by pepa65** [comment]
Thanks for your help. I am perhaps not clear on the terminology.There used to be one bar, with the number of the terminal (status bar?).That I would like to keep. But there is also a tag-bar where the tags are displayed, and that one I don't want to see, because it has no value to me. It seems it is either both hidden or both displayed. I would like to get rid of the line with the tags, but keep the status bar.

**Comment by pepa65** [comment]
OK, found it. What I don't want is called BAR, and setting BAR_POS to BAR_OFF closes this issue!
