### ISSUE TITLE
Shift-up and shift+down don't work either, so I can't select several lines with it in an editor

### ISSUE THREAD

**Issue by evanescente-ondine** [martanne/dvtm#80]
I've made a screenshot for you
![voyez](https://user-images.githubusercontent.com/33675148/34439026-5d03e196-ecab-11e7-9d5b-c36efd451e44.jpg)
Shift-up and shift+down don't work either, so I can't select several lines with it.
shift+up and down in themselves aren't dvtm keybindings, it should be caught.

Thanks for your great work ! Though an .ini config file would suck more... There are people who would like configuring without having to learn C (I learn Ada, it's more than enough !)

**Comment by evanescente-ondine** [comment]
Hello. I should have corrected my post.. what a shame. But it was the first time I posted things in reddit, github etc. I don't think there was an answer to this. Still a problem. I CAN select many line, but it's always ALL line (when ctrl+shift+(up or down]. No problem with Shift+(right or left).
And originally, I meant a INI config file would suck LESS, but I guess the post was still comprehensible.

**Comment by josuah** [comment]
Unfortunate happening: there is a group called suckless.org which publicated a X window manager called suckless configured through a config.h (C header file).  And this is part of the "suckless philosophy" (nothing more than how the people in there like to write their programs).

And DVTM inherited this way of configuring from suckless.

Of course, suckless does not owns the monopole of suck-less-iness. and there are as many ways to suck less as they are people I guess.
