### ISSUE TITLE
Weird recoloring issue with terminals using xterm+256color

### ISSUE THREAD

**Issue by Larivact** [martanne/dvtm#84]
Having `TERM` set to a terminal that uses `xterm+256color` or `xterm+256setaf` (eg. `xterm-256color`) when starting dvtm does two things:

1) Cause the current master branch to hang on startup, showing only an empty screen with a blinking cursor. This can be fixed by merging #82.
2) Causes SGR set color sequences to update all other colored text to the new color. I recommend removing all colors from your prompt to reproduce this.

Steps to reproduce:
```
$ TERM=xterm-256color
$ dvtm
$ PS1='$ '
$ printf '\033[0;31m red \033[0m\n'
red
$ printf '\033[0;32m green \033[0m\n'
green
$ printf '\033[0;33m yellow \033[0m\n'
yellow
```
![dvtmbug](https://user-images.githubusercontent.com/8731884/37588712-5ac37e68-2b63-11e8-923f-b0ef35a19142.gif)

A workaround is to use a terminal that doesn't use  `xterm+256color`, eg. `TERM=dvtm-256color`. You can find out if a terminal uses `xterm+256color` by looking at the [terminfo source](http://invisible-island.net/ncurses/terminfo.src.html).

**Comment by shua** [comment]
PR'd a fix in #85. @Larivact Can you verify if that branch fixes your issue?

**Comment by Larivact** [comment]
Yes #85 fixes this issue and #83 for me. Thank you.

**Comment by seth1** [comment]
Same issue on mlterm-fb -> dvtm, how can I help diagnose this?

**Comment by imlauera** [comment]
This issue is fixed in the new version.
