### ISSUE TITLE
Curses artifacts

### ISSUE THREAD

**Issue by rychipman** [martanne/dvtm#9]
Occasionally while using dvtm, opening a curses application that does not fill up the entire page shows some lines from a previously-open curses session.

In particular, when `git log` does not fill the entire page, there is occasionally some extra text at the top of the screen that appears to be left over from the last time I ran `git log` or from the last time I ran `vim`, whichever was most recent.

**Comment by martanne** [comment]
Since you seem to have a reliable way to reproduce, does [this commit](https://github.com/martanne/dvtm/commit/30701f405718ff00f530e13b974a9e2503b41841) fix it? See also comments in #8 regarding the standard conformance of dvtm's terminal emulation code ...

**Comment by martanne** [comment]
Ping?
